### ISSUE TITLE
Error installing plug-in (error importing pandas)

### ISSUE THREAD

**Issue by yipjackie** [IBIGroupCanWest/CanFlood#6]
After a clean install of QGIS 3.10 (downloaded the long-term release for Mac OS from https://www.qgis.org/en/site/forusers/download.html) and the First Aid plug-in, the installing of the CanFlood plug-in gave an error as shown below - suggesting that it needs pandas 0.25.3 or higher.
<img width="1279" alt="Screen Shot 2020-02-25 at 10 11 54 AM" src="https://user-images.githubusercontent.com/55464195/75369797-f51f2400-5878-11ea-9e22-81b6094ff13e.png">

Also included here the About QGIS page for reference
<img width="1280" alt="Screen Shot 2020-02-26 at 9 14 51 AM" src="https://user-images.githubusercontent.com/55464195/75369905-20a20e80-5879-11ea-913f-8dce85085f5c.png">

**Comment by s4lt3d** [comment]
## Pandas not installed or incorrect version installed
Some versions of QGIS may not come with all required python packages. 

This issue can be solved with two simple commands shown below.


Example Error Message on Windows
![image](https://user-images.githubusercontent.com/1599932/75376479-5c46d380-588d-11ea-9db0-91ea68efc789.png)

## Fixing the issue by installing Pandas manually
Open the Python Console in QGIS
![image](https://user-images.githubusercontent.com/1599932/75376547-77b1de80-588d-11ea-95f7-72ed7fea674c.png)

The Python Console should appear in QGIS and should look similar to to this. 
![image](https://user-images.githubusercontent.com/1599932/75376596-8b5d4500-588d-11ea-97a9-03fddec1d1e0.png)

Type the following commands in the console. 
```python
import pip
pip._internal.main(['install', 'pandas'])
```
![image](https://user-images.githubusercontent.com/1599932/75376736-c2335b00-588d-11ea-941f-bb0f9995772b.png)

![image](https://user-images.githubusercontent.com/1599932/75376747-c8c1d280-588d-11ea-815f-0061b9713644.png)
![image](https://user-images.githubusercontent.com/1599932/75376758-cd868680-588d-11ea-856f-e99f5ff85add.png)

## Conclusion
Running the two commands should correctly install pandas, which will allow CanFlood Alpha to open successfully.

**Comment by yipjackie** [comment]
> ## Pandas not installed or incorrect version installed
> Some versions of QGIS may not come with all required python packages.
> 
> This issue can be solved with two simple commands shown below.
> 
> Example Error Message on Windows
> ![image](https://user-images.githubusercontent.com/1599932/75376479-5c46d380-588d-11ea-9db0-91ea68efc789.png)
> 
> ## Fixing the issue by installing Pandas manually
> Open the Python Console in QGIS
> ![image](https://user-images.githubusercontent.com/1599932/75376547-77b1de80-588d-11ea-95f7-72ed7fea674c.png)
> 
> The Python Console should appear in QGIS and should look similar to to this.
> ![image](https://user-images.githubusercontent.com/1599932/75376596-8b5d4500-588d-11ea-97a9-03fddec1d1e0.png)
> 
> Type the following commands in the console.
> 
> ```python
> import pip
> pip._internal.main(['install', 'pandas'])
> ```
> 
> ![image](https://user-images.githubusercontent.com/1599932/75376736-c2335b00-588d-11ea-941f-bb0f9995772b.png)
> 
> ![image](https://user-images.githubusercontent.com/1599932/75376747-c8c1d280-588d-11ea-815f-0061b9713644.png)
> ![image](https://user-images.githubusercontent.com/1599932/75376758-cd868680-588d-11ea-856f-e99f5ff85add.png)
> 
> ## Conclusion
> Running the two commands should correctly install pandas, which will allow CanFlood Alpha to open successfully.

**Comment by yipjackie** [comment]
Thanks Walter! I've had to modify the command slightly as in the screenshot. I think it shows it is still using pandas 0.24.2 
<img width="975" alt="Screen Shot 2020-02-26 at 3 37 04 PM" src="https://user-images.githubusercontent.com/55464195/75398559-e6536400-58ae-11ea-8a89-3da9beecc3dd.png">

**Comment by cefect** [comment]
Note the pandas version has to be < 1.0.0 to run the Build.EventLikelihoods tool.  This will be fixed in the next release.
